Initial Commit
ishanchawla1/Design-Teardown pull request #1
Opened 2020-03-23 20:13 UTC by ishanchawla1

2020-03-27 18:39 UTC, majovanilla requested changes
Hey @ishanchawla1 , 👋

## You did an *amazing*🌟 ✨ job on this project! 👊🏻  💯

Your page has every element it should have and you are making use of the colors to highlight the important elements. It's almost done!

The next changes are minimum, but still necessary for approving your project.

### Required Changes: ✍️

- [ ] Check the comments below.

- [ ] You don't need to include text in all the elements of your page. It would actually look better in terms of the purpose of the project if you could delete some and leave it in one section (the person of the week, for example) Don't delete from the footer.

## Please, make all REQUIRED changes and submit your request again! 😀

If you have any questions, feel free to send me a message through Slack (@majo)
I would be happy to help! 👩‍💻 


Happy coding 🤓

--Maria Reyes

2020-03-27 18:39 UTC, majovanilla commented on README.md
- [ ] Improve your Readme file. It should be descriptive of the project. You are using the correct template but now you need to fill it with information about your project. You can add details about what you did in this project, why you did it, how you did it...Check this [link](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/) for more info.

2020-03-27 18:39 UTC, majovanilla commented on styles.css
> +}
- [ ] No need to include the % when you use 0.

2020-03-27 18:39 UTC, majovanilla commented on index.html
> +        </nav>
- [ ] The structure of your project should have three main parent tags: nav/header, main and footer. Please take the nav tag outside the main tag.

2020-03-27 22:51 UTC, thsvr commented
### **STATUS: PROJECT APPROVED** :1st_place_medal: :1st_place_medal: :1st_place_medal: 

Hi @ishanchawla1 and @Zubenna :smile_cat: :smile_cat: 

Congrats for the hard work, your project looks amazing :fireworks: :fireworks: :fireworks: 
You guys implemented all the required changes asked by Maria and your project was approved!

**_Optional Suggestions for the next project:_**

:v:  You can create a feature branch with a more descriptive name on the next projects, like ''main-page'' or ''greyscale-page'' instead of ''feature", for example. It will be more descriptive :smile: 

If you have any questions, don't hesitate to contact me through slack [@Thaís Vieira Azevedo](url)

### **Happy coding and good luck on the next project** :computer: 

_Project reviewed by Thaís Vieira (TSE)_

2020-03-28 05:36 UTC, ishanchawla1 commented
Thanks a lot, @majovanilla and @thsvr for the review.

2020-03-28 05:36 UTC, merged